import type { Catalog, Product } from "@/lib/types";

function iqd(usd: number) {
  return Math.round((usd * 1310) / 1000) * 1000;
}

const products: Product[] = [
  {
    id: "cpu-r5-7600",
    category: "cpu",
    name: "Ryzen 5 7600",
    brand: "AMD",
    description: "ستة أنوية ممتازة للألعاب والشغل اليومي، حرارة معقولة وسعر مرتّب.",
    price: iqd(189),
    stock: 8,
    available: true,
    specs: { socket: "AM5", tdp: 65 },
  },
  {
    id: "cpu-r7-7800x3d",
    category: "cpu",
    name: "Ryzen 7 7800X3D",
    brand: "AMD",
    description: "ملك الألعاب حالياً. كاش ثلاثي يرفع الفريمات بشكل واضح.",
    price: iqd(449),
    stock: 4,
    available: true,
    specs: { socket: "AM5", tdp: 120 },
  },
  {
    id: "cpu-r9-7950x",
    category: "cpu",
    name: "Ryzen 9 7950X",
    brand: "AMD",
    description: "١٦ نواة للمونتاج والرندر والبث. يحتاج تبريد قوي.",
    price: iqd(549),
    stock: 3,
    available: true,
    specs: { socket: "AM5", tdp: 170 },
  },
  {
    id: "cpu-i5-14600k",
    category: "cpu",
    name: "Core i5-14600K",
    brand: "Intel",
    description: "أداء عالي للألعاب والمونتاج الخفيف، مع إمكانية رفع التردد.",
    price: iqd(299),
    stock: 6,
    available: true,
    specs: { socket: "LGA1700", tdp: 125 },
  },
  {
    id: "cpu-i7-14700k",
    category: "cpu",
    name: "Core i7-14700K",
    brand: "Intel",
    description: "توازن قوي بين الألعاب وتعدد المهام. مناسب لمحطات العمل المنزلية.",
    price: iqd(409),
    stock: 5,
    available: true,
    specs: { socket: "LGA1700", tdp: 125 },
  },
  {
    id: "cpu-i9-14900k",
    category: "cpu",
    name: "Core i9-14900K",
    brand: "Intel",
    description: "أعلى فئة من إنتل للجيل الحالي. يحتاج كولر ممتاز ومزود طاقة قوي.",
    price: iqd(549),
    stock: 2,
    available: true,
    specs: { socket: "LGA1700", tdp: 253 },
  },
  {
    id: "mb-msi-b650",
    category: "motherboard",
    name: "B650 Gaming Plus WiFi",
    brand: "MSI",
    description: "لوحة AM5 عملية مع واي فاي، منافذ كافية، وسعر مناسب للتجميعات المتوسطة.",
    price: iqd(189),
    stock: 7,
    available: true,
    specs: { socket: "AM5", ramType: "DDR5", formFactor: "ATX" },
  },
  {
    id: "mb-asus-tuf-b650",
    category: "motherboard",
    name: "TUF Gaming B650-PLUS WiFi",
    brand: "ASUS",
    description: "بنية متينة وتبريد VRM جيد. خيار موثوق لرايزن ٧ و٩.",
    price: iqd(219),
    stock: 5,
    available: true,
    specs: { socket: "AM5", ramType: "DDR5", formFactor: "ATX" },
  },
  {
    id: "mb-gigabyte-x670",
    category: "motherboard",
    name: "X670 Aorus Elite AX",
    brand: "Gigabyte",
    description: "فئة أعلى مع منافذ أكثر وPCIe إضافي للي يبي توسعة مستقبلية.",
    price: iqd(289),
    stock: 3,
    available: true,
    specs: { socket: "AM5", ramType: "DDR5", formFactor: "ATX" },
  },
  {
    id: "mb-msi-b760",
    category: "motherboard",
    name: "MAG B760 Tomahawk WiFi",
    brand: "MSI",
    description: "لوحة LGA1700 متينة مع DDR5 وواي فاي ٦. مناسبة لسلسلة i5 و i7.",
    price: iqd(209),
    stock: 6,
    available: true,
    specs: { socket: "LGA1700", ramType: "DDR5", formFactor: "ATX" },
  },
  {
    id: "mb-asus-z790",
    category: "motherboard",
    name: "PRIME Z790-P WiFi",
    brand: "ASUS",
    description: "شريحة Z790 لرفع التردد على معالجات K ودعم ذاكرة أعلى.",
    price: iqd(249),
    stock: 4,
    available: true,
    specs: { socket: "LGA1700", ramType: "DDR5", formFactor: "ATX" },
  },
  {
    id: "mb-asus-b650i",
    category: "motherboard",
    name: "ROG Strix B650-I Gaming WiFi",
    brand: "ASUS",
    description: "لوحة ITX صغيرة لتجميعة مدمجة. تحتاج كيس ITX وكولر مناسب.",
    price: iqd(259),
    stock: 2,
    available: true,
    specs: { socket: "AM5", ramType: "DDR5", formFactor: "ITX" },
  },
  {
    id: "ram-kf-16-6000",
    category: "ram",
    name: "Fury Beast 16GB (2x8) 6000",
    brand: "Kingston",
    description: "كيت ١٦ غيغا DDR5 بسرعة جيدة للبداية. يكفي للألعاب بدقة ١٠٨٠p.",
    price: iqd(79),
    stock: 12,
    available: true,
    specs: { ramType: "DDR5", capacity: "16GB", speed: "6000 MT/s" },
  },
  {
    id: "ram-kf-32-6000",
    category: "ram",
    name: "Fury Beast 32GB (2x16) 6000",
    brand: "Kingston",
    description: "الاختيار الأكثر طلباً. ٣٢ غيغا مريحة للألعاب والكروم والمونتاج الخفيف.",
    price: iqd(129),
    stock: 10,
    available: true,
    specs: { ramType: "DDR5", capacity: "32GB", speed: "6000 MT/s" },
  },
  {
    id: "ram-gskill-32-6400",
    category: "ram",
    name: "Trident Z5 RGB 32GB 6400",
    brand: "G.Skill",
    description: "شكل RGB فخم وتوقيتات أفضل. تظهر جميلة من نافذة الكيس.",
    price: iqd(159),
    stock: 6,
    available: true,
    specs: { ramType: "DDR5", capacity: "32GB", speed: "6400 MT/s" },
  },
  {
    id: "ram-corsair-64-6000",
    category: "ram",
    name: "Vengeance 64GB (2x32) 6000",
    brand: "Corsair",
    description: "للمونتاج الثقيل والآلات الافتراضية. ما راح تحتاج ترقية قريب.",
    price: iqd(229),
    stock: 4,
    available: true,
    specs: { ramType: "DDR5", capacity: "64GB", speed: "6000 MT/s" },
  },
  {
    id: "ram-kf-32-ddr4",
    category: "ram",
    name: "Fury Beast 32GB (2x16) 3200",
    brand: "Kingston",
    description: "DDR4 للوحات القديمة فقط. لا تتركبها على مذربود DDR5.",
    price: iqd(89),
    stock: 5,
    available: true,
    specs: { ramType: "DDR4", capacity: "32GB", speed: "3200 MT/s" },
  },
  {
    id: "gpu-4060",
    category: "gpu",
    name: "GeForce RTX 4060 8GB",
    brand: "NVIDIA",
    description: "دخول ممتاز لألعاب ١٠٨٠p مع DLSS 3 واستهلاك كهرباء منخفض.",
    price: iqd(329),
    stock: 7,
    available: true,
    specs: { wattage: 115, capacity: "8GB" },
  },
  {
    id: "gpu-4060ti",
    category: "gpu",
    name: "GeForce RTX 4060 Ti 16GB",
    brand: "NVIDIA",
    description: "ذاكرة ١٦ غيغا تساعد في المونتاج والألعاب الحديثة بدقة ٢K.",
    price: iqd(459),
    stock: 4,
    available: true,
    specs: { wattage: 165, capacity: "16GB" },
  },
  {
    id: "gpu-4070s",
    category: "gpu",
    name: "GeForce RTX 4070 Super 12GB",
    brand: "NVIDIA",
    description: "الحلوى الحقيقية لـ ١٤٤٠p. أداء قوي وحرارة معقولة.",
    price: iqd(629),
    stock: 5,
    available: true,
    specs: { wattage: 220, capacity: "12GB" },
  },
  {
    id: "gpu-4080s",
    category: "gpu",
    name: "GeForce RTX 4080 Super 16GB",
    brand: "NVIDIA",
    description: "لأصحاب ٤K والريتينغ العالي. كرت كبير يحتاج كيس واسع.",
    price: iqd(1049),
    stock: 2,
    available: true,
    specs: { wattage: 320, capacity: "16GB" },
  },
  {
    id: "gpu-4090",
    category: "gpu",
    name: "GeForce RTX 4090 24GB",
    brand: "NVIDIA",
    description: "أقوى كرت بالجيل. للمونتاج ٨K والألعاب بكل شيء مفتوح.",
    price: iqd(1899),
    stock: 1,
    available: true,
    specs: { wattage: 450, capacity: "24GB" },
  },
  {
    id: "gpu-7800xt",
    category: "gpu",
    name: "Radeon RX 7800 XT 16GB",
    brand: "AMD",
    description: "قيمة ممتازة لذاكرة ١٦ غيغا وأداء ٢K بدون سعر إنفيديا.",
    price: iqd(499),
    stock: 4,
    available: true,
    specs: { wattage: 263, capacity: "16GB" },
  },
  {
    id: "ssd-wd-1tb",
    category: "storage",
    name: "Black SN770 1TB NVMe",
    brand: "WD",
    description: "سرعة Gen4 كافية للنظام والألعاب. تيرا واحد بداية مرتّبة.",
    price: iqd(89),
    stock: 14,
    available: true,
    specs: { capacity: "1TB", speed: "5150 MB/s" },
  },
  {
    id: "ssd-990-1tb",
    category: "storage",
    name: "990 Pro 1TB NVMe",
    brand: "Samsung",
    description: "من أسرع الأقراص للتحميل والنقل. موثوقية سامسونج.",
    price: iqd(129),
    stock: 8,
    available: true,
    specs: { capacity: "1TB", speed: "7450 MB/s" },
  },
  {
    id: "ssd-990-2tb",
    category: "storage",
    name: "990 Pro 2TB NVMe",
    brand: "Samsung",
    description: "٢ تيرا ترتاح فيهم: نظام، ألعاب، ومشاريع مونتاج.",
    price: iqd(189),
    stock: 6,
    available: true,
    specs: { capacity: "2TB", speed: "7450 MB/s" },
  },
  {
    id: "ssd-kingston-2tb",
    category: "storage",
    name: "NV2 2TB NVMe",
    brand: "Kingston",
    description: "مساحة كبيرة بسعر أوفر. ممتاز كقرص ألعاب ثانوي.",
    price: iqd(119),
    stock: 9,
    available: true,
    specs: { capacity: "2TB", speed: "3500 MB/s" },
  },
  {
    id: "ssd-wd-4tb",
    category: "storage",
    name: "Black SN850X 4TB NVMe",
    brand: "WD",
    description: "للمحترفين والمكتبات الكبيرة. سرعة عالية ومساحة ما تخلص بسرعة.",
    price: iqd(329),
    stock: 3,
    available: true,
    specs: { capacity: "4TB", speed: "7300 MB/s" },
  },
  {
    id: "cooler-ag400",
    category: "cooler",
    name: "AG400 Digital",
    brand: "Deepcool",
    description: "هوائي هادئ ورخيص. يكفي لمعالجات ٦٥–١٢٠ واط بدون فخامة.",
    price: iqd(35),
    stock: 11,
    available: true,
    specs: { socket: "AM5 / LGA1700", tdp: 220 },
  },
  {
    id: "cooler-pa120",
    category: "cooler",
    name: "Peerless Assassin 120 SE",
    brand: "Thermalright",
    description: "أفضل قيمة بالهوائي. يبرد حتى المعالجات القوية بهدوء.",
    price: iqd(39),
    stock: 9,
    available: true,
    specs: { socket: "AM5 / LGA1700", tdp: 260 },
  },
  {
    id: "cooler-kraken-240",
    category: "cooler",
    name: "Kraken 240 RGB",
    brand: "NZXT",
    description: "مائي ٢٤٠ ملم مع شاشة دائرية. شكل فخم وتبريد أحسن من الهوائي العادي.",
    price: iqd(129),
    stock: 5,
    available: true,
    specs: { socket: "AM5 / LGA1700", wattage: 240, tdp: 280 },
  },
  {
    id: "cooler-arctic-360",
    category: "cooler",
    name: "Liquid Freezer III 360",
    brand: "Arctic",
    description: "مائي ٣٦٠ ملم للأجهزة الحرّة. ممتاز لـ i9 ورايزن ٩.",
    price: iqd(139),
    stock: 4,
    available: true,
    specs: { socket: "AM5 / LGA1700", wattage: 360, tdp: 300 },
  },
  {
    id: "cooler-nhd15",
    category: "cooler",
    name: "NH-D15",
    brand: "Noctua",
    description: "أسطورة الهوائي. هادئ جداً وطويل العمر، بس حجمه كبير.",
    price: iqd(109),
    stock: 3,
    available: true,
    specs: { socket: "AM5 / LGA1700", tdp: 250 },
  },
  {
    id: "case-cc560",
    category: "case",
    name: "CC560 Mid Tower",
    brand: "Deepcool",
    description: "كيس زجاجي بسعر مرتّب. تهوية كافية وتجميعة واضحة للزبون.",
    price: iqd(69),
    stock: 8,
    available: true,
    specs: { formFactor: "ATX" },
  },
  {
    id: "case-lancool-216",
    category: "case",
    name: "Lancool 216",
    brand: "Lian Li",
    description: "تهوية ممتازة ومساحة للكروت الطويلة. محبوب عند التجميعات القوية.",
    price: iqd(109),
    stock: 5,
    available: true,
    specs: { formFactor: "ATX" },
  },
  {
    id: "case-h5-flow",
    category: "case",
    name: "H5 Flow",
    brand: "NZXT",
    description: "شكل نظيف وواجهة مرتبة. مناسب لمحلات تحب الجهاز يطلع أنيق.",
    price: iqd(99),
    stock: 6,
    available: true,
    specs: { formFactor: "ATX" },
  },
  {
    id: "case-4000d",
    category: "case",
    name: "4000D Airflow",
    brand: "Corsair",
    description: "كلاسيكي سهل التركيب، كيبلات مرتبة، وهواء داخل الجهاز نظيف.",
    price: iqd(104),
    stock: 5,
    available: true,
    specs: { formFactor: "ATX" },
  },
  {
    id: "case-nr200",
    category: "case",
    name: "NR200 Mini-ITX",
    brand: "Cooler Master",
    description: "صغيرة وقوية التهوية. فقط للوحات ITX والكروت بطول مناسب.",
    price: iqd(99),
    stock: 3,
    available: true,
    specs: { formFactor: "ITX" },
  },
  {
    id: "case-fractal-ridge",
    category: "case",
    name: "Ridge Thin Mini-ITX",
    brand: "Fractal",
    description: "كيس نحيف يوقف بجانب الشاشة. تجميعة مكتب أنيقة ومحدودة المساحة.",
    price: iqd(149),
    stock: 2,
    available: true,
    specs: { formFactor: "ITX" },
  },
];

export const seedCatalog: Catalog = {
  settings: {
    whatsapp: "",
    shopNote:
      "الأسعار بـ IQD. التجميعة تُراجع قبل التجهيز، والتوصيل داخل العراق حسب المدينة.",
  },
  products,
};
